mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('rate.urls')),
    url(r'^rate/', include('rate.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/rate/urls.py
from django.conf.urls import url

from . import views

app_name = 'rate'
urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^index/$', views.IndexView.as_view(), name='index'),
    url(r'^forms/$', views.FormsView.as_view(), name='forms'),
    url(r'^modify/$', views.ModifyView.as_view(), name='modify'),
    url(r'^compare/$', views.CompareView, name='compare'),
    url(r'^score/$', views.score, name='score'),
    url(r'^vote/(?P<month>[0-9]+)/$', views.vote, name='vote'),
]

mysite/rate/models.py
from django.db import models

# Create your models here.


class Query(models.Model):
    query = models.CharField(max_length=80, primary_key=True)

    def is_valid(self):
        if self.query['search']:
            return True
        else:
            return False

    def __str__(self):
        return self.query


class ScoreMovie(models.Model):
    score = models.IntegerField(default=1)
    movie = models.CharField(max_length=80, primary_key=True)

    def is_valid(self):
        if self.score['score2'] and self.score['movie2']:
            return True
        else:
            return False

    def __str__(self):
        return self.movie


class Score(models.Model):
    id1 = models.CharField(max_length=40, primary_key=True)
    score = models.IntegerField()

    def is_valid(self):
        if self.id1['id1'] and self.id1['score1']:
            return True
        else:
            return False

    def __str__(self):
        return self.id1

mysite/rate/views.py
from django.shortcuts import render
from django.views import generic
from numpy import mean
from .models import Query, ScoreMovie, Score
from .crawler_api import mongodb
from .crawler_api.crawler import pre_art
from .model import KerasModel
import re
from datetime import datetime
# Create your views here.


model_handler = KerasModel()


class HomeView(generic.TemplateView):
    template_name = 'rate/home.html'


class IndexView(generic.ListView):
    model = Query
    form_class = Query
    template_name = 'rate/index.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            pos_articles, neu_articles, neg_articles = [], [], []
            labeled_score = []
            date_info = []
            example = []
            with mongodb.Mongodb(hash_check=False) as mgd:
                old_articles = mgd.search_title('articles', ''.join(form.query['search'].split()))
                new_articles = mgd.search_title('new_articles', ''.join(form.query['search'].split()))
                total = old_articles + new_articles
                split = len(old_articles)
                if total:
                    date_str = total[len(total) - 1]['date_added']
                    year, month = re.split('[-T]', date_str)[0:2]
                    year = int(year)
                    month = int(month)
                    for i in range(1, 7):
                        post_num = 0
                        for t in total:
                            if int(t['date_added'][0:4]) == year and int(t['date_added'][5:7]) == month:
                                post_num += 1

                        date_info.append([year, month, post_num])
                        month = month - 1
                        if month == 0:
                            year = year - 1
                            month = 12

                    nlp = [t['encode'] for t in total]
                    predict_result = model_handler.predict(nlp)
                    for ori, ft, cl, c2l in zip(total, predict_result['fasttext'], predict_result['cnn_lstm'], predict_result['cnn_2lstm']):
                        ori['fasttext'] = ft
                        ori['cnn_lstm'] = cl
                        ori['cnn_2lstm'] = c2l
                    pos_articles = [t for t in total if t['score'] > 3]
                    neu_articles = [t for t in total if t['score'] == 3]
                    neg_articles = [t for t in total if t['score'] < 3]
                    example.append(pre_art(pos_articles))
                    example.append(pre_art(neu_articles))
                    example.append(pre_art(neg_articles))
                    labeled_score = [t['score'] for t in total]

            try:
                st = datetime.now()
                stat_score = int((sum(labeled_score) / len(labeled_score)) * 21)
                stat_score_time = datetime.now() - st
                articles = len(labeled_score)
                fasttext_score = int(mean(predict_result['fasttext']) * 100)
                fasttext_time = predict_result['fasttext_time']
                cnn_lstm_score = int(mean(predict_result['cnn_lstm']) * 100)
                cnn_lstm_time = predict_result['cnn_lstm_time']
                cnn2lstm_score = int(mean(predict_result['cnn_2lstm']) * 100)
                cnn2lstm_time = predict_result['cnn_2lstm_time']

                if old_articles:
                    old_stat_score = int((sum(labeled_score[:split]) / len(labeled_score[:split])) * 21)
                    old_articles = len(labeled_score[:split])
                    old_fasttext_score = int(mean(predict_result['fasttext'][:split]) * 100)
                    old_cnn_lstm_score = int(mean(predict_result['cnn_lstm'][:split]) * 100)
                    old_cnn2lstm_score = int(mean(predict_result['cnn_2lstm'][:split]) * 100)
                else:
                    old_stat_score = 0
                    old_articles = 0
                    old_fasttext_score = 0
                    old_cnn_lstm_score = 0
                    old_cnn2lstm_score = 0

                if new_articles:
                    new_stat_score = int((sum(labeled_score[split:]) / len(labeled_score[split:])) * 21)
                    new_articles = len(labeled_score[split:])
                    new_fasttext_score = int(mean(predict_result['fasttext'][split:]) * 100)
                    new_cnn_lstm_score = int(mean(predict_result['cnn_lstm'][split:]) * 100)
                    new_cnn2lstm_score = int(mean(predict_result['cnn_2lstm'][split:]) * 100)
                else:
                    new_stat_score = 0
                    new_articles = 0
                    new_fasttext_score = 0
                    new_cnn_lstm_score = 0
                    new_cnn2lstm_score = 0
            except ZeroDivisionError:
                return render(request, self.template_name, {
                    'form': form,
                    'error_message': '請輸入正確電影名稱，若沒輸入錯誤，就是該電影還未加入資料庫請見諒',
                })

            return render(request, self.template_name, {
                'form': form,
                'search_valid': True,
                'query': form.query['search'],

                'old_movie_score': old_stat_score,
                'old_total': old_articles,
                'old_fast_text': old_fasttext_score,
                'old_cnn_lstm': old_cnn_lstm_score,
                'old_cnn_2lstm': old_cnn2lstm_score,

                'mean_dl_score': int(mean([fasttext_score, cnn_lstm_score, cnn2lstm_score])),
                'movie_score': stat_score,
                'total': articles,
                'fast_text': fasttext_score,
                'cnn_lstm': cnn_lstm_score,
                'cnn_2lstm': cnn2lstm_score,

                'new_movie_score': new_stat_score,
                'new_total': new_articles,
                'new_fast_text': new_fasttext_score,
                'new_cnn_lstm': new_cnn_lstm_score,
                'new_cnn_2lstm': new_cnn2lstm_score,

                'total_time': '{:05.2f} sec'.format(stat_score_time.total_seconds()),
                'fast_text_time': '{:05.2f} sec'.format(fasttext_time.total_seconds()),
                'cnn_lstm_time': '{:05.2f} sec'.format(cnn_lstm_time.total_seconds()),
                'cnn_2lstm_time': '{:05.2f} sec'.format(cnn2lstm_time.total_seconds()),

                'pos': len(pos_articles),
                'neg': len(neg_articles),
                'neutral': len(neu_articles),
                'art': example,
                'date_info': date_info,
                'pos_articles': pos_articles,
                'neg_articles': neg_articles,
                'neu_articles': neu_articles
            })

        return render(request, self.template_name, {
            'form': form,
            'error_message': 'Please enter movie name',
        })


class FormsView(generic.TemplateView):
    template_name = 'rate/forms.html'


class ModifyView(generic.ListView):
    model = ScoreMovie
    form_class = ScoreMovie
    template_name = 'rate/modify.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            score = form.score['score2']
            movie = form.score['movie2']
            with mongodb.Mongodb(hash_check=False) as mgd:
                article = mgd.search_dual('articles', 'title', movie, 'score', int(score))
            try:
                article['content'] = article['content'].replace(' ', '\n')
                article['id0'] = article['_id']
                return render(request, self.template_name, article)
            except IndexError:
                return render(request, 'rate/labelfix.html', {'error_message': '資料庫無此電影或沒有該範圍分數的文章'})
            except TypeError:
                return render(request, 'rate/labelfix.html', {'error_message': '資料庫無此電影或沒有該範圍分數的文章'})

        return render(request, 'rate/labelfix.html', {'error_message': 'Not valid input.'})


class CompareView(generic.TemplateView):
    template_name = 'rate/compare.html'


def score(request):
    if request.method == 'POST':
        form = Score(request.POST)

        if form.is_valid():
            id1 = form.id1['id1']
            get_score = form.id1['score1']

            with mongodb.Mongodb(hash_check=False) as mgd:
                mgd.update_score('articles', id1, int(get_score))
                mgd.update_modified(id1)

            return render(request, 'rate/forms.html')

        return render(request, 'rate/home.html', {'form': form, })


def vote(request, month):
    with mongodb.Mongodb(hash_check=False) as mgd:
        lst = mgd.search_month('movie_by_month', '2017/' + month)

    return render(request, 'rate/compare.html', {'test': lst})

mysite/rate/templates/rate/compare.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    {% include "./metas.html" %}
    {% include "./style_sheet.html" %}
    <title>MickeyRat - HomePage</title>

    <link href="{% static 'css/heroic-features.css' %}" rel="stylesheet">

    <link href="{% static 'scrolling-nav.css' %}" rel="stylesheet">
</head>

<body>

<div id="wrapper">

    <!-- Navigation -->
    {% include "./navbar.html" %}

    <!-- Page Content -->

    <div id="page-wrapper">

        <div class="row1 text-center">
            {% for t in test %}
            <div class="col-lg-3-1 col-md-6-1 mb-4">
                <div class="card">
                    <img class="card-img-top" src="data:image/jpeg;base64,{{ t.picture }}" alt="">
                    <div class="card-body">
                        <h3 class="card-title">{{ t.中文片名 }}</h3>
                        {% if t.score.fasttext %}
                        <p class="card-text">類型：{{ t.類型 }}<br>上映：{{ t.台灣上映日期 }}<br>導演：{{ t.導演 }}<br>分數：{{ t.score.fasttext }}</p>
                        {% else %}
                        <p class="card-text">類型：{{ t.類型 }}<br>上映：{{ t.台灣上映日期 }}<br>導演：{{ t.導演 }}<br>分數：NA</p>
                        {% endif %}
                    </div>
                    <div class="card-footer">
                        <form action="{% url 'rate:index' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" value="{{ t.中文片名 }}" name="search">
                            {% if t.score.fasttext %}
                            <button class="btn btn-primary" type="submit">Find Out More!</button>
                            {% else %}
                            <button class="btn btn-primary" type="submit" disabled>Find Out More!</button>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>

    <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

{% include "./down_js.html" %}

</body>

</html>

mysite/rate/templates/rate/down_js.html
{% load static %}
<!-- jQuery -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'vendor/metisMenu/metisMenu.min.js' %}"></script>

<!-- Custom Theme JavaScript -->
<script src="{% static 'dist/js/sb-admin-2.js' %}"></script>

mysite/rate/templates/rate/forms.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    {% include "./metas.html" %}
    {% include "./style_sheet.html" %}
    <title>MickeyRat - Forms</title>
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        {% include "./navbar.html" %}

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">協助改善電影評分</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            這個頁面是讓使用者能直接修改特定電影的評分文章的分數，輸入想找的電影和選擇想看的文章分數後就可以協助修改這些文章的評分
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <form action="{% url 'rate:modify' %}" method="post">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label for="mov2">電影名稱</label>
                                            <input class="form-control" id="mov2" name="movie2">
                                            <p class="help-block">輸入完整電影名稱提供搜尋.</p>
                                        </div>
                                        <div class="form-group">
                                            <label for="sel2">Selects</label>
                                            <select class="form-control" id="sel2" name="score2">
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                                <option>5</option>
                                            </select>
                                            <p class="help-block">請選擇想要看的文章分數(愈高分代表評價愈好)</p>
                                            <p class="help-red">注意:文章是隨機選取的 改過的文章不會重複出現</p>
                                        </div>
                                        <button type="submit" class="btn btn-default">Submit Button</button>
                                        <button type="reset" class="btn btn-default">Reset Button</button>
                                    </form>
                                </div>
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    {% include "./down_js.html" %}

</body>

</html>

mysite/rate/templates/rate/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    {% include "./metas.html" %}
    {% include "./style_sheet.html" %}
    <title>MickeyRat - HomePage</title>

    <link href="{% static 'scrolling-nav.css' %}" rel="stylesheet">
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        {% include "./navbar.html" %}
        <!-- Page Content -->
        <div id="page-wrapper">
            <section id="welcome">
                <div class="container text-center">
                    <div class="row">
                        <div class="col-lg-7 mx-auto">
                            <h1 class="page-header">MickeyRat</h1>
                            <p class="lead" style="font-family: 'Microsoft JhengHei UI'" align="left">MickeyRat是分析PTT電影版文章的一個評分系統,目的在於讓使用者快速得知有興趣的電影在PTT上的評價好壞在左上輸入想找的電影名稱,可以看到正負文章數量及評分和各種圖表分析。</p>
                        </div>
                        <!-- /.col-lg-12 -->
                        <div class="col-lg-2 panel panel-green">
                            <div class="panel-heading">
                                每月電影名單
                            </div>
                            <div class="panel-body">
                                <a href="vote/01">2017/01</a>
                                <br>
                                <a href="vote/02">2017/02</a>
                                <br>
                                <a href="vote/03">2017/03</a>
                                <br>
                                <a href="vote/04">2017/04</a>
                                <br>
                                <a href="vote/05">2017/05</a>
                                <br>
                                <a href="vote/06">2017/06</a>
                                <br>
                                <a href="vote/07">2017/07</a>
                                <br>
                                <a href="vote/08">2017/08</a>
                                <br>
                                <a href="vote/09">2017/09</a>
                                <br>
                                <a href="vote/10">2017/10</a>
                                <br>
                                <a href="vote/11">2017/11</a>
                                <br>
                                <a href="vote/12">2017/12</a>
                            </div>
                        </div>
                    </div>
                    <!-- /.row -->
                </div>
            </section>

            <section id="about" class="bg-light">
                <div class="container text-center">
                    <div class="row">
                        <div class="col-lg-8 mx-auto">
                            <h1 class="page-header">文章資訊</h1>
                            <p class="lead" style="font-family: 'Microsoft JhengHei UI'">視覺化文章相關資訊，讓電影評分一目瞭然</p>
                            <ul style="font-family: 'Microsoft JhengHei UI'">
                                <li>正負文章統計</li>
                                <li>電影總體評分</li>
                                <li>推文趨勢分析</li>
                                <li>文章圖表呈現</li>
                            </ul>
                        </div>
                        <!-- /.col-lg-12 -->
                    </div>
                    <!-- /.row -->
                </div>
            </section>

            <section id="model">
                <div class="container text-center">
                    <div class="row">
                        <div class="col-lg-8 mx-auto">
                            <h1 class="page-header">深度學習模型</h1>
                            <p class="lead" style="font-family: 'Microsoft JhengHei UI'">使用深度學習模型對文章進行訓練，當作文章原始評分的實驗數據</p>
                            <ul style="font-family: 'Microsoft JhengHei UI'">
                                <li>FastText</li>
                                <li>LSTM(100)</li>
                                <li>LSTM(1000)</li>
                            </ul>
                        </div>
                        <!-- /.col-lg-12 -->
                    </div>
                    <!-- /.row -->
                </div>
            </section>
            <!-- /.container-fluid -->
        </div>

        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    {% include "./down_js.html" %}

</body>

</html>

mysite/rate/templates/rate/metas.html
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">

mysite/rate/templates/rate/style_sheet.html
{% load static %}
<!-- Bootstrap Core CSS -->
<link href="{% static 'vendor/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
<!-- MetisMenu CSS -->
<link href="{% static 'vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet">
<!-- Custom CSS -->
<link href="{% static 'dist/css/sb-admin-20.css' %}" rel="stylesheet">
<!-- Custom Fonts -->
<link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<link href="{% static 'auto-complete.css' %}" rel="stylesheet">
<script src="{% static 'auto-complete.js' %}"></script>